[package]
name = "pandt"
version = "0.1.0"
authors = ["Christopher Armstrong <radix@twistedmatrix.com>"]


# [lib]
# name = "pandt"
# path = "src/lib.rs"
#
[[bin]]
name = "pandt-cli"

[dependencies]
serde = "0.8"
serde_derive = "0.8"
serde_json = "0.8"
