[package]
name = "foldertree"
version = "0.1.0"
authors = ["Christopher Armstrong"]
edition = "2021"

[dependencies]
serde = { version = "1.0", optional = true, features = ["derive"] }
thiserror.workspace = true
ts-rs = { version = "12.0.1" }

[dev-dependencies]
serde_json = "1.0"
