[package]
name = "nonempty"
version = "0.1.0"
authors = ["Christopher Armstrong"]

[features]
use_serde = ["serde", "serde_derive"]

[dev-dependencies]
serde_json = "1.0"

[dependencies]
serde = {version = "1.0", optional = true}
serde_derive = {version = "1.0", optional = true}
