name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: rustup target add wasm32-unknown-unknown
    - uses: actions/checkout@v4
    - run: cargo build --verbose
    - run: cargo test --verbose

    - working-directory: arpui
      run: cargo check --target wasm32-unknown-unknown

    - working-directory: arpui
      run: cargo test
